# Generated by Django 5.1.7 on 2025-03-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PO_Items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BUYER', 'Buyer'), ('APPROVER', 'Approver'), ('INVENTORY_MANAGER', 'Inventory Manager')], default='BUYER', max_length=20),
        ),
    ]
