# Generated by Django 5.1.7 on 2025-03-30 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PO_Items', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sportsitem',
            name='supplier',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='PO_Items.supplier'),
            preserve_default=False,
        ),
    ]
